# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Paweł Wiśniewski
subtitle: Consulting
tagline:          ''
email: "&#112;&#97;&#119;&#101;&#108;&#64;&#119;&#105;&#115;&#110;&#105;&#101;&#119;&#115;&#107;&#105;&#46;&#105;&#111;" #pawel@wisniewski.io
tel: "+49 (0) 152 27964620"
description: >- # this means to ignore newlines until "baseurl:"
  Embedded Systeme sicher gemacht
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pawel.wisniewski.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  
xing_username: Pawel_Wisniewski12

google_gtag: "UA-116719785-1"
